# Generated by Django 5.2.8 on 2025-11-21 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('geo_location', models.CharField(blank=True, max_length=255, null=True)),
                ('agent', models.TextField(blank=True, null=True)),
                ('referer', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('request_path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('correlation_token', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('xss_attempted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='XSSAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('pattern', models.CharField(max_length=100)),
                ('raw_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xss_attacks', to='myapp.botevent')),
            ],
        ),
    ]
