# Generated by Django 5.2.8 on 2025-11-21 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_field', models.CharField(max_length=200)),
                ('pattern', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('XSS', 'Cross-Site Scripting'), ('SQLI', 'SQL Injection'), ('LFI', 'Local File Inclusion'), ('CMD', 'Command Injection'), ('TRAVERSAL', 'Directory Traversal'), ('SSTI', 'Template Injection'), ('OTHER', 'Other')], max_length=50, verbose_name='Attack Type')),
                ('raw_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attacks', to='myapp.botevent')),
            ],
        ),
        migrations.DeleteModel(
            name='XSSAttack',
        ),
    ]
