# Generated by Django 5.2.8 on 2025-11-20 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XSSAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('pattern', models.CharField(max_length=255)),
                ('snippet', models.TextField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='botsubmission',
            name='myapp_botsub_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='botsubmission',
            name='myapp_botsub_ip_idx',
        ),
        migrations.RemoveIndex(
            model_name='botsubmission',
            name='myapp_botsub_email_idx',
        ),
        migrations.RenameField(
            model_name='botsubmission',
            old_name='user_agent',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='botsubmission',
            old_name='email_submitted',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='botsubmission',
            name='detection_tags',
        ),
        migrations.RemoveField(
            model_name='botsubmission',
            name='forwarded_for',
        ),
        migrations.RemoveField(
            model_name='botsubmission',
            name='geo',
        ),
        migrations.RemoveField(
            model_name='botsubmission',
            name='headers_json',
        ),
        migrations.RemoveField(
            model_name='botsubmission',
            name='raw_body',
        ),
        migrations.AddField(
            model_name='botsubmission',
            name='full_ip_address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='botsubmission',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='botsubmission',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsubmission',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='botsubmission',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='xssattack',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xss_attacks', to='myapp.botsubmission'),
        ),
    ]
