# Generated by Django 5.2.8 on 2025-11-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_attacktype_delete_xssattack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botevent',
            old_name='xss_attempted',
            new_name='attack_attempted',
        ),
    ]
