# Generated by Django 5.2.8 on 2025-11-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_xss_attempted_botevent_attack_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='botevent',
            name='origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='attack_attempted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=10),
        ),
    ]
