# Generated by Django 5.2.8 on 2025-11-23 13:49

import uuid
from django.db import migrations, models


def _generate_uuids_for_attacktype(apps, schema_editor):
    """Generate UUIDs for all existing AttackType records."""
    AttackType = apps.get_model("myapp", "AttackType")
    for attack in AttackType.objects.all():
        attack.new_id = uuid.uuid4()
        attack.save(update_fields=["new_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_botevent_origin_alter_botevent_attack_attempted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attacktype",
            name="category",
            field=models.CharField(
                choices=[
                    ("XSS", "Cross-Site Scripting"),
                    ("SQLI", "SQL Injection"),
                    ("LFI", "Local File Inclusion"),
                    ("CMD", "Command Injection"),
                    ("TRAVERSAL", "Directory Traversal"),
                    ("SSTI", "Template Injection"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Attack Type",
            ),
        ),
        migrations.AlterField(
            model_name="attacktype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        # Custom migration to convert id from bigint to UUID
        # This requires multiple steps because PostgreSQL can't cast bigint to uuid directly
        # Step 1: Add new UUID field (temporary, nullable)
        migrations.AddField(
            model_name="attacktype",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Generate UUIDs for all existing records
        migrations.RunPython(
            code=_generate_uuids_for_attacktype,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 3: Make new_id NOT NULL
        migrations.AlterField(
            model_name="attacktype",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        # Step 4: Drop the old primary key constraint using raw SQL
        migrations.RunSQL(
            sql="ALTER TABLE myapp_attacktype DROP CONSTRAINT myapp_attacktype_pkey;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 5: Remove old id field
        migrations.RemoveField(
            model_name="attacktype",
            name="id",
        ),
        # Step 6: Rename new_id to id
        migrations.RenameField(
            model_name="attacktype",
            old_name="new_id",
            new_name="id",
        ),
        # Step 7: Add primary key constraint and update Django state
        # Use SeparateDatabaseAndState to add constraint via SQL while updating Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE myapp_attacktype ADD PRIMARY KEY (id);",
                    reverse_sql="ALTER TABLE myapp_attacktype DROP CONSTRAINT myapp_attacktype_pkey;",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="attacktype",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="botevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="botevent",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="botevent",
            name="geo_location",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="botevent",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="botevent",
            name="method",
            field=models.CharField(
                choices=[("GET", "GET"), ("POST", "POST")], db_index=True, max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="botevent",
            name="origin",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="botevent",
            name="referer",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="botevent",
            name="request_path",
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="attacktype",
            index=models.Index(
                fields=["bot_event", "category"], name="attacktype_be_cat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attacktype",
            index=models.Index(
                fields=["category", "created_at"], name="attacktype_cat_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botevent",
            index=models.Index(
                fields=["attack_attempted", "method"], name="botevent_attack_method_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botevent",
            index=models.Index(
                fields=["attack_attempted", "method", "request_path"],
                name="botevent_atk_meth_path_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="botevent",
            index=models.Index(
                fields=["ip_address", "created_at"], name="botevent_ip_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botevent",
            index=models.Index(
                fields=["request_path", "attack_attempted"],
                name="botevent_path_attack_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="botevent",
            index=models.Index(
                fields=["ip_address", "request_path"], name="botevent_ip_path_idx"
            ),
        ),
    ]
