from django.core.management.base import BaseCommand
from myapp.models import BotEvent, AttackType
from myapp.tests.factories import BotEventFactory, AttackTypeFactory
from myapp.enums import MethodChoice
import random


class Command(BaseCommand):
    help = "Generate fake bot data"

    def add_arguments(self, parser):
        parser.add_argument(
            "--bots", type=int, default=100, help="Number of bots to generate"
        )

        parser.add_argument(
            "--attacks",
            type=float,
            default=0.3,
            help="Percentage of bots that will attempt attacks",
        )

    def handle(self, *args, **options):
        num_bots = options["bots"]
        attack_rate = options["attacks"]

        self.stdout.write(
            f"Creating {num_bots} bots with {attack_rate * 100}% attack rate"
        )

        common_ips = ["192.168.1.1", "10.0.0.1", "172.16.0.1", "203.0.113.1"]

        for i in range(num_bots):
            # 30% chance to use a common IP (creates aggregation opportunities)
            if random.random() < 0.3:
                ip = random.choice(common_ips)
            else:
                ip = None

            # Create bot event
            if ip:
                bot_event = BotEventFactory(ip_address=ip)
            else:
                bot_event = BotEventFactory()

            # Some events should be attacks
            if random.random() < attack_rate:
                # Create 1-3 attacks per attacking event
                # The AttackTypeFactory's post_generation hook will automatically:
                # - Update bot_event.data with attack payloads
                # - Set bot_event.attack_attempted = True
                num_attacks = random.randint(1, 3)
                for _ in range(num_attacks):
                    AttackTypeFactory(bot_event=bot_event)

            # Some events should be scan bots (GET, no data, no attack)
            elif random.random() < 0.4:
                bot_event.method = MethodChoice.GET.value
                bot_event.data = None
                bot_event.attack_attempted = False
                bot_event.save()

            # Some events should be spam bots (POST, has data, no attack)
            elif random.random() < 0.3:
                bot_event.method = MethodChoice.POST.value
                # Email is already generated by factory since data is not None
                # Use the existing email in the data dict
                bot_event.data = {"email": bot_event.email, "message": "spam"}
                bot_event.attack_attempted = False
                bot_event.save()

            if (i + 1) % 10 == 0:
                self.stdout.write(f"Created {i + 1}/{num_bots} bots...")

        self.stdout.write(
            self.style.SUCCESS(
                f"\nSuccessfully created {num_bots} bot events!\n"
                f"Total BotEvents: {BotEvent.objects.count()}\n"
                f"Total Attacks: {AttackType.objects.count()}\n"
                f"Events with attacks: {BotEvent.objects.filter(attack_attempted=True).count()}"
            )
        )
